spring:
  cloud:
    gateway:
      routes:
        - id: test-baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test-qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: lowtproduct_route
          uri: lb://lowt-product
          predicates:
            - Path=/api/lowtproduct/**
          filters:
            - RewritePath=/api/lowtproduct/(?<segment>.*), /lowtproduct/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

# 前端项目发送的时候带上 /api
# http://localhost:8099/api/captcha.jpg -> http://localhost:8080/renren-fast/captcha.jpg
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
